// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxsoqsugudvdtxzkxyoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4c29xc3VndWR2ZHR4emt4eW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTc0MDEsImV4cCI6MjA3MTc3MzQwMX0.xLYD2nYMCeUC7fEUdeUT3V4R6QuJwSJq2SUeH36vVu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});